export enum UserErrorType {
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  WEAK_PASSWORD = 'WEAK_PASSWORD',
  UNAUTHORIZED_ROLE = 'UNAUTHORIZED_ROLE',
  INTERNAL_ERROR = 'INTERNAL_ERROR'
}