export const ENDPOINTS = {
  AUTH: {
    GOOGLE_LOGIN: '/api/auth/google',
    LOGIN: '/api/auth/login',
    VERIFY_OTP: '/api/auth/verify-otp',
    ME: '/api/auth/me',
    LOGOUT: '/api/auth/logout',
    FORGOT_PASSWORD: '/api/auth/forgot-password',
    RESET_PASSWORD: '/api/auth/reset-password',
  },
  ANNOUNCEMENTS: {
    BASE: '/api/announcements',
    PUBLIC: '/api/announcements/public',
    BY_ID: (id: string) => `/api/announcements/${id}`,
    PUBLISH: (id: string) => `/api/announcements/${id}/publish`,
    UNPUBLISH: (id: string) => `/api/announcements/${id}/unpublish`,
    PIN: (id: string) => `/api/announcements/${id}/pin`,
  },
  CLASSES: {
    BASE: '/api/classes',
    BY_ID: (id: string) => `/api/classes/${id}`,
    SUBJECTS: (classId: string) => `/api/classes/${classId}/subjects`,
    SUBJECT_BY_ID: (classId: string, subjectId: string) => `/api/classes/${classId}/subjects/${subjectId}`,
    ASSIGN_SUBJECT_TEACHER: (classId: string, subjectId: string) => `/api/classes/${classId}/subjects/${subjectId}/teacher`,
  },
  DEPARTMENTS: {
    BASE: '/api/departments',
    BY_ID: (id: string) => `/api/departments/${id}`,
  },
  EXAMS: {
    BASE: '/api/exams',
    BY_ID: (id: string) => `/api/exams/${id}`,
    COMMON_SUBJECTS: (examId: string) => `/api/exams/${examId}/grades/subjects`,
    REMOVE_COMMON_SUBJECT: (examId: string, grade: string, subjectId: string) => `/api/exams/${examId}/grades/${grade}/subjects/${subjectId}`,
    SECTION_LANGUAGES: (examId: string) => `/api/exams/${examId}/grades/languages`,
    REMOVE_SECTION_LANGUAGE: (examId: string, grade: string, classId: string) => `/api/exams/${examId}/grades/${grade}/languages/${classId}`,
    PUBLISH: (examId: string) => `/api/exams/${examId}/publish`,
    DECLARE: (examId: string) => `/api/exams/${examId}/declare`,
    SCHEDULES: (examId: string) => `/api/exams/${examId}/schedules`,
    MARKS: '/api/exams/marks',
    MARKS_BY_SCHEDULE: (scheduleId: string) => `/api/exams/schedules/${scheduleId}/marks`,
    MY_PENDING_MARKS: '/api/exams/pending-marks/me',
    CLASS_RESULTS: (examId: string, classId: string) => `/api/exams/${examId}/results/${classId}`,
    MY_SCHEDULES_FOR_CLASS: (classId: string) => `/api/exams/class/${classId}/my-schedules`,
    MY_SUBMITTED_MARKS: '/api/exams/submitted-marks/me',
    STUDENT_RESULTS: (studentId: string) => `/api/exams/student/${studentId}/results`,
  },
  MANAGERS: {
    BASE: '/api/managers',
    BY_ID: (id: string) => `/api/managers/${id}`,
    WHITELIST: '/api/admins/whitelist',
    BLOCK: (id: string) => `/api/admins/managers/${id}/block`,
    UNBLOCK: (id: string) => `/api/admins/managers/${id}/unblock`,
  },
  STATS: {
    OVERVIEW: '/api/stats/overview',
    GRADE_PERFORMANCE: '/api/stats/grade-performance',
    STUDENT: (id: string) => `/api/stats/student/${id}`,
  },
  STUDENTS: {
    BASE: '/api/students',
    BY_ID: (id: string) => `/api/students/${id}`,
    ASSIGN_CLASS: (id: string) => `/api/students/${id}/class`,
    RESET_PASSWORD: (id: string) => `/api/auth/students/${id}/reset-password`,
  },
  SUBJECTS: {
    BASE: '/api/subjects',
    BY_ID: (id: string) => `/api/subjects/${id}`,
  },
  TEACHERS: {
    BASE: '/api/teachers',
    BY_ID: (id: string) => `/api/teachers/${id}`,
    ME: '/api/teachers/me',
    MY_CLASSES: '/api/teachers/me/classes',
    REACTIVATE: (id: string) => `/api/teachers/${id}/reactivate`,
    DEPARTMENT: (id: string) => `/api/teachers/${id}/department`,
    BY_SUBJECT: (subjectId: string) => `/api/teachers/by-subject/${subjectId}`,
    BY_LEVEL: (level: string) => `/api/teachers/by-level/${level}`,
  },
  TOPPERS: {
    BASE: '/api/toppers',
    PUBLIC: '/api/toppers/public',
    BY_ID: (id: string) => `/api/toppers/${id}`,
    PUBLISH: (id: string) => `/api/toppers/${id}/publish`,
    UNPUBLISH: (id: string) => `/api/toppers/${id}/unpublish`,
    UPLOAD_IMAGE: '/api/upload/image',
  },
} as const;
